# Generated by Django 4.2.7 on 2023-12-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=120)),
                ('title_ar', models.CharField(blank=True, max_length=120)),
                ('title_en', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateField(auto_now=True)),
                ('content_fa', models.CharField(blank=True, max_length=1000000)),
                ('content_ar', models.CharField(blank=True, max_length=1000000)),
                ('content_en', models.CharField(blank=True, max_length=1000000)),
            ],
            options={
                'db_table': 'post',
                'ordering': ['created_at'],
            },
        ),
    ]
