# Generated by Django 4.2.7 on 2023-11-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=120)),
                ('title_ar', models.CharField(blank=True, max_length=120)),
                ('title_en', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateField(auto_now=True)),
                ('content_fa', models.CharField(blank=True, max_length=1000000)),
                ('content_ar', models.CharField(blank=True, max_length=1000000)),
                ('content_en', models.CharField(blank=True, max_length=1000000)),
            ],
            options={
                'db_table': 'article',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=20)),
                ('name_ar', models.CharField(blank=True, max_length=20)),
                ('name_en', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
    ]
