# Generated by Django 4.2.7 on 2023-11-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.CharField(max_length=1000)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/article')),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'article',
                'ordering': ['created_at'],
            },
        ),
    ]
