# Generated by Django 4.2.7 on 2023-11-28 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
        ('comment', '0001_initial'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='article', to='comment.comment'),
        ),
        migrations.AddField(
            model_name='article',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='article', to='media.photo'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='article', to='article.tags'),
        ),
    ]
