# Generated by Django 4.2.7 on 2023-12-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=20, unique=True)),
                ('name_ar', models.CharField(blank=True, max_length=20, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=20, unique=True)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
    ]
