# Generated by Django 4.2.7 on 2023-12-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(max_length=1000, upload_to='photos')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
    ]
